import { defineAdminContractManifest } from "../admin-contract-manifest";

export const machinesInventoryAdminContractManifest =
  defineAdminContractManifest({
    slice: "machines-inventory",
    controllerPaths: [
      "apps/service-api/src/machines/machines.controller.ts",
      "apps/service-api/src/machines/qweather-config.controller.ts",
      "apps/service-api/src/inventory/inventory.controller.ts",
      "apps/service-api/src/inventory/stock-reconciliation.controller.ts",
    ],
    callerPaths: [
      "apps/admin-ui/src/api/machines.ts",
      "apps/admin-ui/src/api/qweather.ts",
      "apps/admin-ui/src/api/inventory.ts",
    ],
    contracts: {
      adminListMachinesContract: {
        method: "GET",
        path: "/machines",
        providerMethod: "listMachines",
        callerPath: "apps/admin-ui/src/api/machines.ts",
        callerMethods: ["listMachines"],
      },
      adminCreateMachineContract: {
        method: "POST",
        path: "/machines",
        providerMethod: "createMachine",
        callerPath: "apps/admin-ui/src/api/machines.ts",
        callerMethods: ["createMachine"],
      },
      adminUpdateMachineContract: {
        method: "PATCH",
        path: "/machines/:id",
        providerMethod: "updateMachine",
        callerPath: "apps/admin-ui/src/api/machines.ts",
        callerMethods: ["updateMachine"],
      },
      adminGetMachineContract: {
        method: "GET",
        path: "/machines/:id",
        providerMethod: "getMachine",
        callerPath: "apps/admin-ui/src/api/machines.ts",
        callerMethods: ["getMachine"],
      },
      adminGetMachineExternalNaturalEnvironmentContract: {
        method: "GET",
        path: "/machines/:id/external-natural-environment",
        providerMethod: "getExternalNaturalEnvironment",
        callerPath: "apps/admin-ui/src/api/machines.ts",
        callerMethods: ["getExternalNaturalEnvironment"],
      },
      adminPublishMachinePlanogramVersionContract: {
        method: "POST",
        path: "/machines/:id/planogram-versions",
        providerMethod: "publishPlanogramVersion",
      },
      adminListMachinePlanogramVersionsContract: {
        method: "GET",
        path: "/machines/:id/planogram-versions",
        providerMethod: "listPlanogramVersions",
      },
      adminCommandMachineEnvironmentContract: {
        method: "POST",
        path: "/machines/:id/commands/environment-control",
        providerMethod: "commandEnvironment",
        callerPath: "apps/admin-ui/src/api/machines.ts",
        callerMethods: ["commandEnvironment"],
      },
      adminListMachineSlotsContract: {
        method: "GET",
        path: "/machines/:id/slots",
        providerMethod: "listSlots",
        callerPath: "apps/admin-ui/src/api/machines.ts",
        callerMethods: ["listMachineSlots"],
      },
      adminCreateMachineSlotContract: {
        method: "POST",
        path: "/machines/:id/slots",
        providerMethod: "createSlot",
        callerPath: "apps/admin-ui/src/api/machines.ts",
        callerMethods: ["createMachineSlot"],
      },
      adminRotateMachineCredentialsContract: {
        method: "POST",
        path: "/machines/:id/credentials/rotate",
        providerMethod: "rotateMachineCredentials",
        callerPath: "apps/admin-ui/src/api/machines.ts",
        callerMethods: ["rotateMachineCredentials"],
      },
      adminSecureDecommissionMachineContract: {
        method: "POST",
        path: "/machines/:id/decommission",
        providerMethod: "secureDecommission",
      },
      adminGenerateMachineClaimCodeContract: {
        method: "POST",
        path: "/machines/:id/claim-codes",
        providerMethod: "generateClaimCode",
        callerPath: "apps/admin-ui/src/api/machines.ts",
        callerMethods: ["generateMachineClaimCode"],
      },
      adminListMachineClaimCodesContract: {
        method: "GET",
        path: "/machines/:id/claim-codes",
        providerMethod: "listClaimCodes",
        callerPath: "apps/admin-ui/src/api/machines.ts",
        callerMethods: ["listMachineClaimCodes"],
      },
      adminGetMachineClaimCodeContract: {
        method: "GET",
        path: "/machines/:id/claim-codes/:claimCodeId",
        providerMethod: "getClaimCode",
      },
      adminRevokeMachineClaimCodeContract: {
        method: "POST",
        path: "/machines/:id/claim-codes/:claimCodeId/revoke",
        providerMethod: "revokeClaimCode",
        callerPath: "apps/admin-ui/src/api/machines.ts",
        callerMethods: ["revokeMachineClaimCode"],
      },
      adminGetQweatherConfigContract: {
        method: "GET",
        path: "/qweather-config",
        providerMethod: "getConfig",
        callerPath: "apps/admin-ui/src/api/qweather.ts",
        callerMethods: ["getQweatherConfig"],
      },
      adminUpdateQweatherConfigContract: {
        method: "PUT",
        path: "/qweather-config",
        providerMethod: "updateConfig",
        callerPath: "apps/admin-ui/src/api/qweather.ts",
        callerMethods: ["updateQweatherConfig"],
      },
      adminListInventoriesContract: {
        method: "GET",
        path: "/inventories",
        providerMethod: "listInventories",
        callerPath: "apps/admin-ui/src/api/inventory.ts",
        callerMethods: ["listInventories"],
      },
      adminCreateInventoryContract: {
        method: "POST",
        path: "/inventories",
        providerMethod: "createInventory",
        callerPath: "apps/admin-ui/src/api/inventory.ts",
        callerMethods: ["createInventory"],
      },
      adminAdjustInventoryContract: {
        method: "POST",
        path: "/inventories/adjust",
        providerMethod: "adjust",
        callerPath: "apps/admin-ui/src/api/inventory.ts",
        callerMethods: ["adjustInventory"],
      },
      adminListInventoryMovementsContract: {
        method: "GET",
        path: "/inventory-movements",
        providerMethod: "listMovements",
        callerPath: "apps/admin-ui/src/api/inventory.ts",
        callerMethods: ["listInventoryMovements"],
      },
      adminListStockReconciliationCasesContract: {
        method: "GET",
        path: "/stock-reconciliation-cases",
        providerMethod: "listCases",
        callerPath: "apps/admin-ui/src/api/inventory.ts",
        callerMethods: ["listStockReconciliationCases"],
      },
      adminGetStockReconciliationCaseContract: {
        method: "GET",
        path: "/stock-reconciliation-cases/:id",
        providerMethod: "getCase",
        callerPath: "apps/admin-ui/src/api/inventory.ts",
        callerMethods: ["getStockReconciliationCase"],
      },
      adminResolveStockReconciliationCaseContract: {
        method: "POST",
        path: "/stock-reconciliation-cases/:id/resolve",
        providerMethod: "resolveCase",
        callerPath: "apps/admin-ui/src/api/inventory.ts",
        callerMethods: ["resolveStockReconciliationCase"],
      },
    },
  });
