import { defineAdminContractManifest } from "../admin-contract-manifest";

export const paymentsAdminContractManifest = defineAdminContractManifest({
  slice: "payments",
  controllerPaths: [
    "apps/service-api/src/payments/payments.controller.ts",
    "apps/service-api/src/payments/payment-ops.controller.ts",
    "apps/service-api/src/payments/payment-code.controller.ts",
  ],
  callerPaths: ["apps/admin-ui/src/api/payments.ts"],
  contracts: {
    adminListPaymentsContract: {
      method: "GET",
      path: "/payments",
      providerMethod: "listPayments",
      callerPath: "apps/admin-ui/src/api/payments.ts",
      callerMethods: ["listPayments"],
    },
    adminMockPaymentSucceedContract: {
      method: "POST",
      path: "/payments/mock/:paymentNo/succeed",
      providerMethod: "markMockSucceeded",
      callerPath: "apps/admin-ui/src/api/payments.ts",
      callerMethods: ["mockSucceed"],
    },
    adminMockPaymentFailContract: {
      method: "POST",
      path: "/payments/mock/:paymentNo/fail",
      providerMethod: "markMockFailed",
      callerPath: "apps/admin-ui/src/api/payments.ts",
      callerMethods: ["mockFail"],
    },
    adminListPaymentProvidersContract: {
      method: "GET",
      path: "/payments/providers",
      providerMethod: "listProviders",
      callerPath: "apps/admin-ui/src/api/payments.ts",
      callerMethods: ["listPaymentProviders"],
    },
    adminUpdatePaymentProviderContract: {
      method: "PATCH",
      path: "/payments/providers/:id",
      providerMethod: "updateProvider",
      callerPath: "apps/admin-ui/src/api/payments.ts",
      callerMethods: ["updatePaymentProvider"],
    },
    adminListPaymentProviderConfigsContract: {
      method: "GET",
      path: "/payments/provider-configs",
      providerMethod: "listProviderConfigs",
      callerPath: "apps/admin-ui/src/api/payments.ts",
      callerMethods: ["listPaymentProviderConfigs"],
    },
    adminListPaymentProviderNotifyUrlChecksContract: {
      method: "GET",
      path: "/payments/provider-configs/notify-url-checks",
      providerMethod: "listProviderNotifyUrlChecks",
      callerPath: "apps/admin-ui/src/api/payments.ts",
      callerMethods: ["listPaymentProviderNotifyUrlChecks"],
    },
    adminUpdatePaymentProviderConfigContract: {
      method: "PATCH",
      path: "/payments/provider-configs/:id",
      providerMethod: "updateProviderConfig",
      callerPath: "apps/admin-ui/src/api/payments.ts",
      callerMethods: ["updatePaymentProviderConfig"],
    },
    adminUpsertPaymentProviderConfigContract: {
      method: "POST",
      path: "/payments/provider-configs",
      providerMethod: "upsertProviderConfig",
      callerPath: "apps/admin-ui/src/api/payments.ts",
      callerMethods: ["upsertPaymentProviderConfig"],
    },
    adminGetPaymentChannelPolicyContract: {
      method: "GET",
      path: "/payments/channel-policy",
      providerMethod: "getChannelPolicy",
      callerPath: "apps/admin-ui/src/api/payments.ts",
      callerMethods: ["getPaymentChannelPolicy"],
    },
    adminUpdatePaymentChannelPolicyContract: {
      method: "PUT",
      path: "/payments/channel-policy",
      providerMethod: "updateChannelPolicy",
      callerPath: "apps/admin-ui/src/api/payments.ts",
      callerMethods: ["updatePaymentChannelPolicy"],
    },
    adminListPaymentEventsContract: {
      method: "GET",
      path: "/payments/events",
      providerMethod: "listPaymentEvents",
      callerPath: "apps/admin-ui/src/api/payments.ts",
      callerMethods: ["listPaymentEvents"],
    },
    adminListPaymentWebhookAttemptsContract: {
      method: "GET",
      path: "/payments/webhook-attempts",
      providerMethod: "listWebhookAttempts",
      callerPath: "apps/admin-ui/src/api/payments.ts",
      callerMethods: ["listWebhookAttempts"],
    },
    adminListPaymentReconciliationAttemptsContract: {
      method: "GET",
      path: "/payments/reconciliation-attempts",
      providerMethod: "listReconciliationAttempts",
      callerPath: "apps/admin-ui/src/api/payments.ts",
      callerMethods: ["listReconciliationAttempts"],
    },
    adminCreatePaymentIncidentActionContract: {
      method: "POST",
      path: "/payments/:id/incident-actions",
      providerMethod: "paymentIncidentAction",
      callerPath: "apps/admin-ui/src/api/payments.ts",
      callerMethods: ["createPaymentIncidentAction"],
    },
    adminManualReconcilePaymentContract: {
      method: "POST",
      path: "/payments/:id/reconcile",
      providerMethod: "manualReconcile",
      callerPath: "apps/admin-ui/src/api/payments.ts",
      callerMethods: ["manualReconcile"],
    },
    adminListPaymentRefundsContract: {
      method: "GET",
      path: "/payments/refunds",
      providerMethod: "listRefunds",
      callerPath: "apps/admin-ui/src/api/payments.ts",
      callerMethods: ["listRefunds"],
    },
    adminQueryPaymentRefundContract: {
      method: "POST",
      path: "/payments/refunds/:id/query",
      providerMethod: "queryRefund",
      callerPath: "apps/admin-ui/src/api/payments.ts",
      callerMethods: ["queryRefund"],
    },
    adminListPaymentCodeAttemptsContract: {
      method: "GET",
      path: "/payments/payment-code-attempts",
      providerMethod: "listAttempts",
      callerPath: "apps/admin-ui/src/api/payments.ts",
      callerMethods: ["listPaymentCodeAttempts"],
    },
    adminQueryPaymentCodeAttemptContract: {
      method: "POST",
      path: "/payments/payment-code-attempts/:id/query",
      providerMethod: "queryAttempt",
      callerPath: "apps/admin-ui/src/api/payments.ts",
      callerMethods: ["queryPaymentCodeAttempt"],
    },
    adminReversePaymentCodeAttemptContract: {
      method: "POST",
      path: "/payments/payment-code-attempts/:id/reverse",
      providerMethod: "reverseAttempt",
      callerPath: "apps/admin-ui/src/api/payments.ts",
      callerMethods: ["reversePaymentCodeAttempt"],
    },
    adminGetPaymentMachinePreflightContract: {
      method: "GET",
      path: "/payments/ops/machines/:machineId/preflight",
      providerMethod: "getMachinePreflight",
      callerPath: "apps/admin-ui/src/api/payments.ts",
      callerMethods: ["getPaymentMachinePreflight"],
    },
    adminGetPaymentOpsReadinessContract: {
      method: "GET",
      path: "/payments/ops/readiness",
      providerMethod: "getReadiness",
    },
    adminGetPaymentOpsMetricsContract: {
      method: "GET",
      path: "/payments/ops/metrics",
      providerMethod: "getMetrics",
    },
  },
});
