import { defineAdminContractManifest } from "../admin-contract-manifest";

export const tryOnAdminContractManifest = defineAdminContractManifest({
  slice: "try-on",
  controllerPaths: [
    "apps/service-api/src/products/products.controller.ts",
    "apps/service-api/src/media-assets/media-assets.controller.ts",
    "apps/service-api/src/try-on-garments/try-on-garments.controller.ts",
  ],
  callerPaths: [
    "apps/admin-ui/src/api/products.ts",
    "apps/admin-ui/src/api/try-on-garments.ts",
  ],
  contracts: {
    adminProductDisplayImageUploadContract: {
      method: "POST",
      path: "/media-assets/product-display-images",
      providerMethod: "uploadProductDisplayImage",
      callerPath: "apps/admin-ui/src/api/products.ts",
      callerMethods: ["uploadProductDisplayImage"],
      schemaReferences: { responseSchema: ["adminMediaAssetSummarySchema"] },
    },
    adminListProductsContract: {
      method: "GET",
      path: "/products",
      providerMethod: "listProducts",
      callerPath: "apps/admin-ui/src/api/products.ts",
      callerMethods: ["listProducts"],
      schemaReferences: {
        pathParamsSchema: ["noProductPathParamsSchema"],
        querySchema: ["adminProductListQuerySchema"],
        bodySchema: ["noProductBodySchema"],
        responseSchema: ["adminProductPageResponseSchema"],
      },
    },
    adminCreateProductContract: {
      method: "POST",
      path: "/products",
      providerMethod: "createProduct",
      callerPath: "apps/admin-ui/src/api/products.ts",
      callerMethods: ["createProduct"],
      schemaReferences: {
        pathParamsSchema: ["noProductPathParamsSchema"],
        querySchema: ["noProductQuerySchema"],
        bodySchema: ["createProductSchema"],
        responseSchema: ["adminProductResponseSchema"],
      },
    },
    adminUpdateProductContract: {
      method: "PATCH",
      path: "/products/:id",
      providerMethod: "updateProduct",
      callerPath: "apps/admin-ui/src/api/products.ts",
      callerMethods: ["updateProduct"],
      schemaReferences: {
        pathParamsSchema: ["productIdPathParamsSchema"],
        querySchema: ["noProductQuerySchema"],
        bodySchema: ["updateProductSchema"],
        responseSchema: ["adminProductResponseSchema"],
      },
    },
    adminListProductVariantsContract: {
      method: "GET",
      path: "/product-variants",
      providerMethod: "listVariants",
      callerPath: "apps/admin-ui/src/api/products.ts",
      callerMethods: ["listProductVariants"],
      schemaReferences: {
        pathParamsSchema: ["noProductPathParamsSchema"],
        querySchema: ["adminProductVariantListQuerySchema"],
        bodySchema: ["noProductBodySchema"],
        responseSchema: ["adminProductVariantPageResponseSchema"],
      },
    },
    adminCreateProductVariantContract: {
      method: "POST",
      path: "/product-variants",
      providerMethod: "createVariant",
      callerPath: "apps/admin-ui/src/api/products.ts",
      callerMethods: ["createProductVariant"],
      schemaReferences: {
        pathParamsSchema: ["noProductPathParamsSchema"],
        querySchema: ["noProductQuerySchema"],
        bodySchema: ["createProductVariantSchema"],
        responseSchema: ["adminProductVariantResponseSchema"],
      },
    },
    adminUpdateProductVariantContract: {
      method: "PATCH",
      path: "/product-variants/:id",
      providerMethod: "updateVariant",
      callerPath: "apps/admin-ui/src/api/products.ts",
      callerMethods: ["updateProductVariant"],
      schemaReferences: {
        pathParamsSchema: ["productIdPathParamsSchema"],
        querySchema: ["noProductQuerySchema"],
        bodySchema: ["updateProductVariantSchema"],
        responseSchema: ["adminProductVariantResponseSchema"],
      },
    },
    adminTryOnGarmentUploadContract: {
      method: "POST",
      path: "/media-assets/try-on-garments",
      providerMethod: "uploadTryOnGarment",
      callerPath: "apps/admin-ui/src/api/try-on-garments.ts",
      callerMethods: ["uploadTryOnGarment"],
      schemaReferences: {
        querySchema: ["noQuerySchema"],
        responseSchema: ["tryOnGarmentMediaAssetSchema"],
      },
    },
    adminCreateTryOnGarmentContract: {
      method: "POST",
      path: "/try-on-garments",
      providerMethod: "createDraft",
      callerPath: "apps/admin-ui/src/api/try-on-garments.ts",
      callerMethods: ["createTryOnGarmentDraft"],
      schemaReferences: {
        querySchema: ["noQuerySchema"],
        bodySchema: ["tryOnGarmentDraftRequestSchema"],
        responseSchema: ["tryOnGarmentResponseSchema"],
      },
    },
    adminGetTryOnGarmentContract: {
      method: "GET",
      path: "/try-on-garments/:id",
      providerMethod: "getById",
      callerPath: "apps/admin-ui/src/api/try-on-garments.ts",
      callerMethods: ["getTryOnGarment"],
      schemaReferences: {
        pathParamsSchema: ["garmentPathParamsSchema"],
        querySchema: ["noQuerySchema"],
        bodySchema: ["noBodySchema"],
        responseSchema: ["tryOnGarmentResponseSchema"],
      },
    },
    adminListTryOnGarmentsByProductContract: {
      method: "GET",
      path: "/try-on-garments",
      providerMethod: "listByProduct",
      callerPath: "apps/admin-ui/src/api/try-on-garments.ts",
      callerMethods: ["listTryOnGarmentsByProduct"],
      schemaReferences: {
        querySchema: ["garmentListQuerySchema"],
        bodySchema: ["noBodySchema"],
        responseSchema: ["tryOnGarmentListResponseSchema"],
      },
    },
    adminTryOnGarmentConfirmationContract: {
      method: "POST",
      path: "/try-on-garments/:id/confirmation",
      providerMethod: "confirm",
      callerPath: "apps/admin-ui/src/api/try-on-garments.ts",
      callerMethods: ["confirmTryOnGarment"],
      schemaReferences: {
        pathParamsSchema: ["garmentPathParamsSchema"],
        querySchema: ["noQuerySchema"],
        bodySchema: ["noBodySchema"],
        responseSchema: ["tryOnGarmentResponseSchema"],
      },
    },
    adminTryOnGarmentActivationContract: {
      method: "POST",
      path: "/try-on-garments/:id/activation",
      providerMethod: "activate",
      callerPath: "apps/admin-ui/src/api/try-on-garments.ts",
      callerMethods: ["activateTryOnGarment"],
      schemaReferences: {
        pathParamsSchema: ["garmentPathParamsSchema"],
        querySchema: ["noQuerySchema"],
        bodySchema: ["noBodySchema"],
        responseSchema: ["tryOnGarmentResponseSchema"],
      },
    },
    adminTryOnGarmentRetirementContract: {
      method: "POST",
      path: "/try-on-garments/:id/retirement",
      providerMethod: "retire",
      callerPath: "apps/admin-ui/src/api/try-on-garments.ts",
      callerMethods: ["retireTryOnGarment"],
      schemaReferences: {
        pathParamsSchema: ["garmentPathParamsSchema"],
        querySchema: ["noQuerySchema"],
        bodySchema: ["noBodySchema"],
        responseSchema: ["tryOnGarmentResponseSchema"],
      },
    },
    adminTryOnGarmentAssociationContract: {
      method: "PUT",
      path: "/try-on-garments/:id/variant-associations",
      providerMethod: "replaceVariantAssociations",
      callerPath: "apps/admin-ui/src/api/try-on-garments.ts",
      callerMethods: ["replaceTryOnGarmentVariantAssociations"],
      schemaReferences: {
        pathParamsSchema: ["garmentPathParamsSchema"],
        querySchema: ["noQuerySchema"],
        bodySchema: ["tryOnGarmentVariantAssociationRequestSchema"],
        responseSchema: ["tryOnGarmentResponseSchema"],
      },
    },
    adminTryOnGarmentSourceReplacementContract: {
      method: "PATCH",
      path: "/try-on-garments/:id/source",
      providerMethod: "replaceSource",
      callerPath: "apps/admin-ui/src/api/try-on-garments.ts",
      callerMethods: ["replaceTryOnGarmentSource"],
      schemaReferences: {
        pathParamsSchema: ["garmentPathParamsSchema"],
        querySchema: ["noQuerySchema"],
        bodySchema: ["tryOnGarmentSourceReplacementRequestSchema"],
        responseSchema: ["tryOnGarmentResponseSchema"],
      },
    },
  },
});
