import type { App as VueApp, Component } from "vue";

import {
  Alert,
  App,
  Button,
  Card,
  Checkbox,
  CheckboxGroup,
  Col,
  ConfigProvider,
  Descriptions,
  DescriptionsItem,
  Divider,
  Drawer,
  Empty,
  Form,
  FormItem,
  Input,
  InputNumber,
  InputPassword,
  Layout,
  LayoutContent,
  LayoutHeader,
  LayoutSider,
  Menu,
  MenuItem,
  Modal,
  Result,
  Row,
  Select,
  SelectOption,
  Space,
  Spin,
  Statistic,
  Switch,
  Table,
  TabPane,
  Tabs,
  Tag,
  TextArea,
  Timeline,
  TimelineItem,
  Typography,
  TypographyText,
} from "antdv-next";

const components: Array<[string, Component]> = [
  ["AAlert", Alert],
  ["AApp", App],
  ["AButton", Button],
  ["ACard", Card],
  ["ACheckbox", Checkbox],
  ["ACheckboxGroup", CheckboxGroup],
  ["ACol", Col],
  ["AConfigProvider", ConfigProvider],
  ["ADescriptions", Descriptions],
  ["ADescriptionsItem", DescriptionsItem],
  ["ADivider", Divider],
  ["ADrawer", Drawer],
  ["AEmpty", Empty],
  ["AForm", Form],
  ["AFormItem", FormItem],
  ["AInput", Input],
  ["AInputNumber", InputNumber],
  ["AInputPassword", InputPassword],
  ["ALayout", Layout],
  ["ALayoutContent", LayoutContent],
  ["ALayoutHeader", LayoutHeader],
  ["ALayoutSider", LayoutSider],
  ["AMenu", Menu],
  ["AMenuItem", MenuItem],
  ["AModal", Modal],
  ["AResult", Result],
  ["ARow", Row],
  ["ASelect", Select],
  ["ASelectOption", SelectOption],
  ["ASpace", Space],
  ["ASpin", Spin],
  ["AStatistic", Statistic],
  ["ASwitch", Switch],
  ["ATable", Table],
  ["ATabPane", TabPane],
  ["ATabs", Tabs],
  ["ATag", Tag],
  ["ATextarea", TextArea],
  ["ATimeline", Timeline],
  ["ATimelineItem", TimelineItem],
  ["ATypography", Typography],
  ["ATypographyText", TypographyText],
];

export function installAntdv(app: VueApp): void {
  for (const [name, component] of components) {
    app.component(name, component);
  }
}
