import {
  invalidVisionV2Fixtures,
  validVisionV2Fixtures,
} from "@vem/shared/fixtures/vision-v2";
import {
  VISION_V2_BUNDLE_VERSION,
  VISION_V2_BUNDLE_SCHEMA_VERSION,
  VISION_V2_PROTOCOL,
  visionV2MessageSchema,
} from "@vem/shared/schemas/vision-v2";
import { createHash } from "node:crypto";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

type Mode = "write" | "check";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const sourceBundle = resolve(root, "packages/shared/generated/vision-v2");
const sourceManifestModule = resolve(
  root,
  "packages/shared/src/generated/vision-v2-bundle.ts",
);

function compareCodePoints(left: string, right: string): number {
  if (left === right) return 0;
  return left < right ? -1 : 1;
}

function canonicalJson(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`;
  if (value && typeof value === "object") {
    return `{${Object.entries(value as Record<string, unknown>)
      .sort(([left], [right]) => compareCodePoints(left, right))
      .map(([key, nested]) => `${JSON.stringify(key)}:${canonicalJson(nested)}`)
      .join(",")}}`;
  }
  return JSON.stringify(value);
}

function sha256(value: string): string {
  return createHash("sha256").update(value).digest("hex");
}

function generatedPythonModels(): string {
  return `# @generated by scripts/vision-v2-contracts/generate-bundle.ts
from __future__ import annotations

import json
import math
import re
from pathlib import Path
from typing import Annotated, Any, Literal, Union
from urllib.parse import urlparse

from jsonschema import Draft202012Validator, FormatChecker
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, TypeAdapter, create_model

PROTOCOL = "${VISION_V2_PROTOCOL}"
CONTRACT_BUNDLE_VERSION = "${VISION_V2_BUNDLE_VERSION}"

# This module has no hand-maintained message or field map. The adjacent JSON
# Schema is generated from VEM Shared Zod and constructs each strict Pydantic
# payload and envelope model at import time.
_SCHEMA_PATH = Path(__file__).resolve().parents[1] / "vision-v2.schema.json"
_SCHEMA = json.loads(_SCHEMA_PATH.read_text(encoding="utf-8"))
_SCHEMA_VALIDATOR = Draft202012Validator(_SCHEMA, format_checker=FormatChecker())

class StrictModel(BaseModel):
    model_config = ConfigDict(extra="forbid", strict=True)

def _model_name(value: str) -> str:
    return "".join(part.capitalize() for part in value.replace(".", "_").split("_"))

def _schema_type(schema: dict[str, Any], name: str) -> Any:
    if "const" in schema:
        return Literal[schema["const"]]
    if "enum" in schema:
        return Literal[tuple(schema["enum"])]
    kind = schema.get("type")
    if kind == "string":
        return StrictStr
    if kind == "integer":
        return StrictInt
    if kind == "boolean":
        return StrictBool
    if kind == "array":
        return list[_schema_type(schema["items"], f"{name}Item")]
    if kind == "object":
        required = set(schema.get("required", []))
        fields = {
            field_name: (
                _schema_type(field_schema, f"{name}{_model_name(field_name)}"),
                ... if field_name in required else None,
            )
            for field_name, field_schema in schema.get("properties", {}).items()
        }
        model = create_model(name, __base__=StrictModel, **fields)
        globals()[name] = model
        return model
    raise ValueError(f"unsupported generated schema type for {name}: {kind}")

def _normalize_json_integers(value: Any, schema: dict[str, Any]) -> Any:
    if "oneOf" in schema and isinstance(value, dict):
        message_type = value.get("type")
        for branch in schema["oneOf"]:
            if branch.get("properties", {}).get("type", {}).get("const") == message_type:
                return _normalize_json_integers(value, branch)
        return value
    if schema.get("type") == "integer":
        if isinstance(value, bool):
            raise ValueError("JSON integer fields reject booleans")
        if isinstance(value, int):
            return value
        if isinstance(value, float) and math.isfinite(value) and value.is_integer():
            return int(value)
        raise ValueError("JSON integer fields require a finite integer")
    if schema.get("type") == "array" and isinstance(value, list):
        return [_normalize_json_integers(item, schema["items"]) for item in value]
    if schema.get("type") == "object" and isinstance(value, dict):
        return {
            key: _normalize_json_integers(item, schema["properties"][key])
            if key in schema.get("properties", {})
            else item
            for key, item in value.items()
        }
    return value

def _validate_extensions(value: Any, schema: dict[str, Any]) -> None:
    if "oneOf" in schema and isinstance(value, dict):
        message_type = value.get("type")
        for branch in schema["oneOf"]:
            if branch.get("properties", {}).get("type", {}).get("const") == message_type:
                _validate_extensions(value, branch)
                return
        return
    if schema.get("description") == "vem.tokenized-loopback-url":
        try:
            parsed = urlparse(value)
            port = parsed.port
        except (TypeError, ValueError) as error:
            raise ValueError("reference must be a valid loopback URL") from error
        if (
            parsed.scheme not in {"http", "https"}
            or parsed.hostname not in {"127.0.0.1", "localhost", "::1"}
            or parsed.username is not None
            or parsed.password is not None
            or (port is not None and not 1 <= port <= 65535)
            or parsed.fragment
            or not parsed.query.startswith("token=")
            or "&" in parsed.query
            or re.fullmatch(schema["pattern"], value) is None
        ):
            raise ValueError("reference must be a tokenized loopback URL")
        return
    if schema.get("type") == "array" and isinstance(value, list):
        for item in value:
            _validate_extensions(item, schema["items"])
    if schema.get("type") == "object" and isinstance(value, dict):
        for key, item in value.items():
            if key in schema.get("properties", {}):
                _validate_extensions(item, schema["properties"][key])

_MESSAGE_MODELS = tuple(
    _schema_type(branch, _model_name(branch["properties"]["type"]["const"]) + "Envelope")
    for branch in _SCHEMA["oneOf"]
)
for _message_model in _MESSAGE_MODELS:
    globals()[_message_model.__name__] = _message_model
VisionV2Envelope = Annotated[Union[tuple(_MESSAGE_MODELS)], Field(discriminator="type")]
_MESSAGE_ADAPTER = TypeAdapter(VisionV2Envelope)

def parse_message(value: Any) -> VisionV2Envelope:
    normalized = _normalize_json_integers(value, _SCHEMA)
    error = next(iter(_SCHEMA_VALIDATOR.iter_errors(normalized)), None)
    if error is not None:
        raise ValueError(f"invalid {PROTOCOL} message: {error.message}")
    _validate_extensions(normalized, _SCHEMA)
    return _MESSAGE_ADAPTER.validate_python(normalized)
`;
}

function bundleFiles(): Map<string, string> {
  const schema = visionV2MessageSchema.toJSONSchema();
  return new Map([
    ["__init__.py", "# @generated VEM Vision V2 bundle package\n"],
    ["vision-v2.schema.json", `${canonicalJson(schema)}\n`],
    ["fixtures/valid.json", `${canonicalJson(validVisionV2Fixtures)}\n`],
    ["fixtures/invalid.json", `${canonicalJson(invalidVisionV2Fixtures)}\n`],
    ["python/__init__.py", "# @generated VEM Vision V2 Python models\n"],
    ["python/vision_v2_models.py", generatedPythonModels()],
  ]);
}

function manifest(files: Map<string, string>): string {
  const fileDigests = Object.fromEntries(
    [...files.entries()].map(([path, contents]) => [path, sha256(contents)]),
  );
  const metadata = {
    schemaVersion: VISION_V2_BUNDLE_SCHEMA_VERSION,
    protocol: VISION_V2_PROTOCOL,
    bundleVersion: VISION_V2_BUNDLE_VERSION,
    files: fileDigests,
  };
  return `${canonicalJson({
    ...metadata,
    bundleDigest: sha256(canonicalJson(metadata)),
  })}\n`;
}

function expectedFiles(): Map<string, string> {
  const files = bundleFiles();
  files.set("manifest.json", manifest(files));
  return files;
}

function generatedManifestModule(): string {
  const contents = expectedFiles().get("manifest.json");
  if (!contents) throw new Error("Vision V2 manifest was not generated");
  const parsed = JSON.parse(contents) as {
    bundleDigest: string;
    bundleVersion: string;
    protocol: string;
    schemaVersion: string;
  };
  return `// @generated by scripts/vision-v2-contracts/generate-bundle.ts\nexport const visionV2BundleManifest = ${canonicalJson(parsed)} as const;\n\n/** Runtime handshake identity; every field is derived from manifest bytes. */\nexport const VISION_V2_RUNTIME_IDENTITY = {\n  protocol: visionV2BundleManifest.protocol,\n  schemaVersion: visionV2BundleManifest.schemaVersion,\n  bundleVersion: visionV2BundleManifest.bundleVersion,\n  contractDigest: visionV2BundleManifest.bundleDigest,\n} as const;\n\nexport const VISION_V2_CONTRACT_DIGEST =\n  VISION_V2_RUNTIME_IDENTITY.contractDigest;\n`;
}

function applyFile(path: string, contents: string, mode: Mode): string[] {
  if (existsSync(path) && readFileSync(path, "utf8") === contents) return [];
  if (mode === "write") {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, contents, "utf8");
  }
  return [path];
}

function existingFiles(target: string): string[] {
  if (!existsSync(target)) return [];
  return readdirSync(target, { withFileTypes: true }).flatMap((entry) => {
    if (entry.name === "__pycache__") return [];
    const path = join(target, entry.name);
    if (entry.isDirectory()) {
      return existingFiles(path).map((nested) => join(entry.name, nested));
    }
    return entry.isFile() ? [relative(target, path)] : [];
  });
}

function applyBundle(target: string, mode: Mode): string[] {
  const expected = expectedFiles();
  const mismatches: string[] = [];
  for (const [relativePath, contents] of expected) {
    const path = join(target, relativePath);
    if (!existsSync(path) || readFileSync(path, "utf8") !== contents) {
      mismatches.push(path);
      if (mode === "write") {
        mkdirSync(dirname(path), { recursive: true });
        writeFileSync(path, contents, "utf8");
      }
    }
  }
  for (const path of existingFiles(target)) {
    if (!expected.has(path.replaceAll("\\", "/"))) {
      mismatches.push(join(target, path));
    }
  }
  return mismatches;
}

function argumentsFrom(argv: string[]): {
  mode: Mode;
  visionRoot: string | undefined;
  sourceOutput: string;
} {
  const mode: Mode = argv.includes("--check") ? "check" : "write";
  const sourceIndex = argv.indexOf("--source-output");
  const sourceOutput =
    sourceIndex >= 0 && argv[sourceIndex + 1]
      ? resolve(argv[sourceIndex + 1])
      : sourceBundle;
  if (argv.includes("--local-only")) {
    return { mode, visionRoot: undefined, sourceOutput };
  }
  const visionIndex = argv.indexOf("--vision-root");
  const visionRoot =
    visionIndex >= 0 && argv[visionIndex + 1]
      ? resolve(argv[visionIndex + 1])
      : resolve(root, "../vending-vision");
  return { mode, visionRoot, sourceOutput };
}

export function generateVisionV2Bundle(
  mode: Mode,
  visionRoot: string | undefined,
  sourceOutput = sourceBundle,
): { changed: string[] } {
  const targets = [
    sourceOutput,
    ...(visionRoot ? [join(visionRoot, "contracts/vem_vision_v2")] : []),
  ];
  const changed = [
    ...targets.flatMap((target) => applyBundle(target, mode)),
    ...applyFile(sourceManifestModule, generatedManifestModule(), mode),
  ];
  if (mode === "check" && changed.length > 0) {
    throw new Error(
      `Vision V2 contract bundle drifted:\n${changed.join("\n")}\nRun pnpm generate:vision-v2-contracts -- ${visionRoot ? `--vision-root ${visionRoot}` : "--local-only"}`,
    );
  }
  return { changed };
}

if (
  process.argv[1] &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  const { mode, visionRoot, sourceOutput } = argumentsFrom(
    process.argv.slice(2),
  );
  try {
    const result = generateVisionV2Bundle(mode, visionRoot, sourceOutput);
    if (mode === "write") {
      process.stdout.write(
        `wrote ${result.changed.length} Vision V2 bundle files\n`,
      );
    }
  } catch (error) {
    process.stderr.write(
      `${error instanceof Error ? error.message : String(error)}\n`,
    );
    process.exitCode = 1;
  }
}
