import { spawnSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
  invalidCurrentDaemonIpcTransactionSnapshots,
  validCurrentDaemonIpcTransactionSnapshots,
} from "../../packages/shared/src/fixtures/daemon-ipc-transaction";
import { exportDaemonIpcTransactionCheckoutJsonSchema } from "../../packages/shared/src/schemas/daemon-ipc";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const crateRoot = resolve(repoRoot, "crates/daemon-ipc-contracts");
const schemaPath = resolve(
  crateRoot,
  "schemas/transaction_checkout.schema.json",
);
const generatedPath = resolve(
  crateRoot,
  "src/generated/transaction_checkout.rs",
);
const validFixturePath = resolve(
  crateRoot,
  "tests/fixtures/transaction_checkout_valid.snapshots.json",
);
const invalidFixturePath = resolve(
  crateRoot,
  "tests/fixtures/transaction_checkout_invalid.snapshots.json",
);

function writeJson(path: string, value: unknown) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`);
}

function getCargoTypifyVersion(): string {
  const version = spawnSync("cargo", ["typify", "--version"], {
    cwd: repoRoot,
    encoding: "utf8",
  });

  if (version.status !== 0) {
    throw new Error(
      [
        "cargo typify --version failed for Daemon IPC transaction checkout generation",
        version.stdout,
        version.stderr,
      ]
        .filter(Boolean)
        .join("\n"),
    );
  }

  const actualVersion = version.stdout.trim();
  const expectedVersion = "cargo-typify 0.7.0";
  if (actualVersion !== expectedVersion) {
    throw new Error(
      `Expected ${expectedVersion} for Daemon IPC transaction checkout generation, got ${actualVersion}`,
    );
  }

  return actualVersion;
}

writeJson(schemaPath, exportDaemonIpcTransactionCheckoutJsonSchema());
writeJson(
  validFixturePath,
  Object.values(validCurrentDaemonIpcTransactionSnapshots),
);
writeJson(
  invalidFixturePath,
  Object.entries(invalidCurrentDaemonIpcTransactionSnapshots).map(
    ([name, snapshot]) => ({ name, snapshot }),
  ),
);

const cargoTypifyVersion = getCargoTypifyVersion();
const typify = spawnSync(
  "cargo",
  [
    "typify",
    "--no-builder",
    "--additional-derive",
    "PartialEq",
    "--output",
    generatedPath,
    schemaPath,
  ],
  {
    cwd: repoRoot,
    encoding: "utf8",
  },
);

if (typify.status !== 0) {
  throw new Error(
    [
      "cargo typify failed for Daemon IPC transaction checkout schema",
      typify.stdout,
      typify.stderr,
    ]
      .filter(Boolean)
      .join("\n"),
  );
}

const generatedHeader = [
  "// @generated by scripts/daemon-ipc-contracts/generate-transaction-checkout.ts",
  "// Source: packages/shared/src/schemas/daemon-ipc.ts via Zod 4 JSON Schema export.",
  `// Generator: ${cargoTypifyVersion}. Do not edit by hand.`,
  "#![allow(dead_code)]",
  "",
].join("\n");

const generated = readFileSync(generatedPath, "utf8");
writeFileSync(generatedPath, `${generatedHeader}${generated}`);
