import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { describe, expect, it } from "vitest";

import {
  buildDaemonIpcTransactionCheckoutInputs,
  generateDaemonIpcTransactionCheckoutContracts,
} from "./generate-transaction-checkout";

describe("Daemon IPC transaction checkout generator", () => {
  it("exports Zod JSON Schema and shared fixtures as generator inputs", () => {
    const inputs = buildDaemonIpcTransactionCheckoutInputs();

    expect(inputs.schema.$schema).toBe(
      "https://json-schema.org/draft/2020-12/schema",
    );
    expect(inputs.schema.title).toBe("CurrentTransactionSnapshot");
    expect(inputs.schema).toHaveProperty("$defs.CheckoutFlowAction");
    expect(JSON.stringify(inputs.schema)).not.toContain("submit_payment");
    expect(JSON.stringify(inputs.schema)).not.toContain("collect_goods");
    expect(inputs.validFixtures.length).toBeGreaterThan(0);
    expect(inputs.invalidFixtures.map((fixture) => fixture.name)).toContain(
      "legacySubmitPaymentAction",
    );
  });

  it("orchestrates schema, fixture, and Rust generation without requiring git state", async () => {
    const root = await mkdtemp(join(tmpdir(), "vem-daemon-ipc-generator-"));
    const spawnCalls: Array<{ command: string; args: string[]; cwd: string }> =
      [];

    try {
      const result = generateDaemonIpcTransactionCheckoutContracts({
        mode: "write",
        repoRoot: root,
        spawnSync(command, args, options) {
          spawnCalls.push({
            command,
            args: [...args],
            cwd: options.cwd,
          });
          if (args.includes("--version")) {
            return {
              status: 0,
              stdout: "cargo-typify 0.7.0\n",
              stderr: "",
            };
          }

          const outputIndex = args.indexOf("--output");
          const outputPath = args[outputIndex + 1];
          mkdirSync(dirname(outputPath), { recursive: true });
          writeFileSync(outputPath, "#![allow(clippy::needless_lifetimes)]\n");
          return {
            status: 0,
            stdout: `generated ${outputPath}`,
            stderr: "",
          };
        },
      });

      expect(result.changedPaths).toEqual([]);
      expect(spawnCalls).toEqual([
        {
          command: "cargo",
          args: ["typify", "--version"],
          cwd: root,
        },
        expect.objectContaining({
          command: "cargo",
          args: expect.arrayContaining([
            "typify",
            "--no-builder",
            "--additional-derive",
            "PartialEq",
          ]),
          cwd: root,
        }),
      ]);

      const schema = JSON.parse(
        readFileSync(
          join(
            root,
            "crates/daemon-ipc-contracts/schemas/transaction_checkout.schema.json",
          ),
          "utf8",
        ),
      );
      expect(schema.title).toBe("CurrentTransactionSnapshot");

      const generated = readFileSync(
        join(
          root,
          "crates/daemon-ipc-contracts/src/generated/transaction_checkout.rs",
        ),
        "utf8",
      );
      expect(generated).toContain(
        "// @generated by scripts/daemon-ipc-contracts/generate-transaction-checkout.ts",
      );
      expect(generated).toContain("Do not edit by hand.");
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });

  it("fails check mode when committed generated output is stale", async () => {
    const root = await mkdtemp(join(tmpdir(), "vem-daemon-ipc-generator-"));

    try {
      const spawnSync = (
        _command: string,
        args: string[],
        _options: { cwd: string; encoding: "utf8" },
      ) => {
        if (args.includes("--version")) {
          return {
            status: 0,
            stdout: "cargo-typify 0.7.0\n",
            stderr: "",
          };
        }

        const outputIndex = args.indexOf("--output");
        const outputPath = args[outputIndex + 1];
        mkdirSync(dirname(outputPath), { recursive: true });
        writeFileSync(outputPath, "pub struct Regenerated;\n");
        return { status: 0, stdout: "", stderr: "" };
      };

      generateDaemonIpcTransactionCheckoutContracts({
        mode: "write",
        repoRoot: root,
        spawnSync,
      });
      writeFileSync(
        join(
          root,
          "crates/daemon-ipc-contracts/src/generated/transaction_checkout.rs",
        ),
        "manually edited generated output\n",
      );

      expect(() =>
        generateDaemonIpcTransactionCheckoutContracts({
          mode: "check",
          repoRoot: root,
          spawnSync,
        }),
      ).toThrow(
        /Daemon IPC generated contracts are stale[\s\S]*src\/generated\/transaction_checkout\.rs/,
      );
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });
});
